stdout of test 'tst054` in directory 'monetdb5/mal` itself:


# 11:11:08 >  
# 11:11:08 >   mserver5 "--config=/ufs/mk/current//Linux/etc/monetdb5.conf" --debug=10 --set gdk_nr_threads=0 --set "monet_mod_path=/ufs/mk/current//Linux/lib/MonetDB5:/ufs/mk/current//Linux/lib/MonetDB5/lib:/ufs/mk/current//Linux/lib/MonetDB5/bin" --set "gdk_dbfarm=/ufs/mk/current//Linux/var/MonetDB5/dbfarm"  --set mapi_open=true --set xrpc_open=true --set mapi_port=31658 --set xrpc_port=44186 --set monet_prompt= --set mal_listing=2 --trace  --dbname=mTests_src_mal  tst054.mal
# 11:11:08 >  

# MonetDB server v5.21.0, based on kernel v1.39.0
# Serving database 'mTests_src_mal', using 4 threads
# Compiled for x86_64-unknown-linux-gnu/64bit with 64bit OIDs dynamically linked
# Found 7.751 GiB available main-memory.
# Copyright (c) 1993-July 2008 CWI.
# Copyright (c) August 2008-2013 MonetDB B.V., all rights reserved
# Visit http://monetdb.cwi.nl/ for further information
# Listening for connection requests on mapi:monetdb://eir.ins.cwi.nl:31658/
# MonetDB/SQL module v2.39.0 loaded
# MonetDB/GIS module v0.19.0 loaded
!SyntaxException:parseError:return (1,2,3,4,5,6,7,8,9,0,1,2,3,4,5,6,7,8,9,0,1,2,3,4,5,6,7,8,9,0);
!SyntaxException:parseError:       ^<identifier> expected
function user.z() (X_1:int,X_2:int,X_3:int,X_4:int,X_5:int,X_6:int,X_7:int,X_8:int,X_9:int,X_10:int,X_11:int,X_12:int,X_13:int,X_14:int,X_15:int,X_16:int,X_17:int,X_18:int,X_19:int,X_20:int,X_21:int,X_22:int,X_23:int,X_24:int,X_25:int,X_26:int,X_27:int,X_28:int,X_29:int,X_30:int);
    io.print("hello");
end z;
!TypeException:user.main[1]:'user.z' undefined in: _1:any := user.z()
function user.main():void;
    user.z();
end main;

# 11:11:08 >  
# 11:11:08 >  Done.
# 11:11:08 >  

