stdout of test 'tst308` in directory 'monetdb5/mal` itself:


# 09:52:07 >  
# 09:52:07 >  Mtimeout -timeout 60 mserver5 "--config=/ufs/mk/monet5/src/mal/Tests/All.conf" --debug=10 --set "monet_mod_path=/ufs/mk/monet5/Linux/lib/MonetDB5:/ufs/mk/opensource/MonetDB/Linux/lib/MonetDB" --set "gdk_dbfarm=/ufs/mk/monet5/Linux/var/MonetDB5/dbfarm" --set "sql_logdir=/ufs/mk/monet5/Linux/var/MonetDB5/dblogs" --set mapi_port=34443 --set monet_prompt= --trace "--config=/ufs/mk/monet5/src/mal/Tests/All.conf" --dbname=mTests_src_mal  tst308.mal < /dev/null
# 09:52:07 >  

# Monet Database Server V4.99.19
# Copyright (c) 1993-2006, CWI. All rights reserved.
# Compiled for x86_64-redhat-linux-gnu/64bit with 64bit OIDs; dynamically linked.
# config:/ufs/mk/monet5/src/mal/Tests/All.conf
# dbfarm:/ufs/mk/monet5/Linux/var/MonetDB5/dbfarm
# dbname:mTests_src_mal
# Visit http://monetdb.cwi.nl/ for further information.
## exception variables are implicitly defined
## by the catch statement.
#
#catch NotDefinedException;
#	io.print("Shouldn't do this");
#	io.print(NotDefineException);
#exit NotDefinedException;
#end foo;
function user.foo():void;
catch NotDefinedException:str ;
    io.print("Shouldn't do this");
    io.print(NotDefinedException);
exit NotDefinedException:str ;
end foo;
#
function user.main():void;
# exception variables are implicitly defined 
# by the catch statement. 
end main;

# 09:52:07 >  
# 09:52:07 >  Done.
# 09:52:07 >  

