#testing exceptions raised in the kernel

b:= bat.new(:oid,:int);
z:= algebra.find(b,0@0);
io.print("should not come here anymore");
catch MALException:str;
	io.print("caught the exception");
exit MALException;
