stdout of test 'tst303` in directory 'monetdb5/mal` itself:


# 08:01:15 >  
# 08:01:15 >  Mtimeout -timeout 60 Mserver "--config=/ufs/mk/monet5/Linux/etc/MonetDB5.conf" --debug=10 --set "monet_mod_path=/ufs/mk/monet5/Linux/lib/MonetDB5:/ufs/mk/opensource/MonetDB/Linux/lib/MonetDB" --set "gdk_dbfarm=/ufs/mk/monet5/Linux/var/MonetDB5/dbfarm" --set "sql_logdir=/ufs/mk/monet5/Linux/var/MonetDB5/log" --set mapi_port=42158 --set sql_port=55708 --set monet_prompt= --trace "--config=/ufs/mk/monet5/src/mal/Tests/All.conf" --dbname=mTests_src_mal  tst303.mal </dev/null
# 08:01:15 >  

# Monet Database Server V4.99.19
# Copyright (c) 1993-2004, CWI. All rights reserved.
# Compiled for i686-redhat-linux-gnu/32bit; dynamically linked.
# config:/ufs/mk/monet5/Linux/etc/MonetDB5.conf
# dbfarm:/ufs/mk/monet5/Linux/var/MonetDB5/dbfarm
# dbname:mTests_src_mal
# Visit http://monetdb.cwi.nl/ for further information.
## recursively raise an exception passed upward
#raise	IllegalAccess := "an exception";
#	print("should not come here\n");
#catch	IllegalAccess;
#	printf("caught %s\n",IllegalAccess);
#raise	IllegalAccess:= "a second exception raised\n";
#	print("should not come here either\n");
#exit	IllegalAccess;
#	print("should not be done");
#
function user.main():void;
# recursively raise an exception passed upward 
    raise IllegalAccess := "an exception";
    io.print("should not come here\n");
catch IllegalAccess;
    io.printf("caught %s\n",IllegalAccess);
    raise IllegalAccess := "a second exception raised";
    io.print("should not come here either\n");
exit IllegalAccess;
    io.print("should not be done");
end main;
caught an exception
!MALException:user.main[6]:a second exception raised
!MALException:user.main[10]:Exception not caught

# 17:45:29 >  
# 17:45:29 >  Done.
# 17:45:29 >  

